/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const argmax: (a: number, b: number) => number;
export const argmin: (a: number, b: number) => number;
export const avg_pooling_2d: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const batch_normalize: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const conv2d_optimized: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const conv2d_scalar: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const cosine_similarity_scalar: (a: number, b: number, c: number, d: number) => number;
export const cosine_similarity_simd: (a: number, b: number, c: number, d: number) => number;
export const dequantize_int8: (a: number, b: number, c: number) => [number, number];
export const dot_product_scalar: (a: number, b: number, c: number, d: number) => number;
export const dot_product_simd: (a: number, b: number, c: number, d: number) => number;
export const euclidean_distance: (a: number, b: number, c: number, d: number) => number;
export const leaky_relu: (a: number, b: number, c: number) => [number, number];
export const lz4_compress_optimized: (a: number, b: number) => [number, number];
export const lz4_compress_scalar: (a: number, b: number) => [number, number];
export const manhattan_distance: (a: number, b: number, c: number, d: number) => number;
export const matrix_add: (a: number, b: number, c: number, d: number) => [number, number];
export const matrix_multiply_scalar: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const matrix_multiply_tiled: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const matrix_scalar_multiply: (a: number, b: number, c: number) => [number, number];
export const matrix_transpose: (a: number, b: number, c: number, d: number) => [number, number];
export const max_pooling_2d: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const mean: (a: number, b: number) => number;
export const quantize_int8_scalar: (a: number, b: number, c: number) => [number, number];
export const quantize_int8_simd: (a: number, b: number, c: number) => [number, number];
export const relu: (a: number, b: number) => [number, number];
export const sigmoid: (a: number, b: number) => [number, number];
export const softmax: (a: number, b: number) => [number, number];
export const std_dev: (a: number, b: number) => number;
export const variance: (a: number, b: number) => number;
export const vector_clamp: (a: number, b: number, c: number, d: number) => [number, number];
export const vector_elementwise_multiply: (a: number, b: number, c: number, d: number) => [number, number];
export const vector_max: (a: number, b: number) => number;
export const vector_min: (a: number, b: number) => number;
export const vector_norm_scalar: (a: number, b: number) => number;
export const vector_norm_simd: (a: number, b: number) => number;
export const vector_normalize: (a: number, b: number) => [number, number];
export const vector_subtract: (a: number, b: number, c: number, d: number) => [number, number];
export const vector_sum: (a: number, b: number) => number;
export const vector_add: (a: number, b: number, c: number, d: number) => [number, number];
export const vector_scale: (a: number, b: number, c: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
